version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - 8081:8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  the-app-1:
    build: ./the-app
    environment:
      - APP_NAME="The App 1"